//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinConfigScan {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinConfigScan.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Both &quot;Application&quot; and &quot;Web&quot; config files can be tested here, but the only visible inherited connection strings will be those from the machine.config. Use &quot;IIS Web Sites&quot; tab if you want to see all inherited  connection strings for a particular web application..
        /// </summary>
        public static string APP_CONFIG_INHERITANCE_NOTE {
            get {
                return ResourceManager.GetString("APP_CONFIG_INHERITANCE_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- INHERITED --.
        /// </summary>
        public static string CONFIG_SOURCE_INHERITED_TEXT {
            get {
                return ResourceManager.GetString("CONFIG_SOURCE_INHERITED_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient rights.
        ///Please run as administrator to access functionality in this tab..
        /// </summary>
        public static string WEB_CONFIG_RIGHTS_NOTE {
            get {
                return ResourceManager.GetString("WEB_CONFIG_RIGHTS_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;connectionStrings&gt;
        ///  &lt;!-- Put connectionStrings here. --&gt;
        ///&lt;/connectionStrings&gt;.
        /// </summary>
        public static string XML_CONFIG_DEFAULT_TEXT {
            get {
                return ResourceManager.GetString("XML_CONFIG_DEFAULT_TEXT", resourceCulture);
            }
        }
    }
}
